add 09 file

diff --git a/.github/workflows/09-function.yaml b/.github/workflows/09-function.yaml
--- a/.github/workflows/09-function.yaml
+++ b/.github/workflows/09-function.yaml
@@ -2,10 +2,23 @@ name:
 
 on:
       pull_request:
+      workflow_dispatch:
 
 jobs:
       echo1:
             runs-on: ubuntu-latest
             steps:
                   - name: Failing step
-                  run: exit 1
+                    run: exit 1
+                  - name: I will be skipped
+                    if: ${{ success() }}
+                    run: echo "I will print if privious steps succeed."
+                  - name: I will execute
+                    if: ${{ failure() }}
+                    run: echo "I will print if any previous step fails."
+                  - name: I will execute
+                    if: ${{ !cancelled() }}
+                    run: echo "I will always print, except when the workflow is cancelled."
+                  - name: I will execute when cancelled
+                    if: ${{ cancelled() }}
+                    run: echo "I will print, if the workflow has been cancelled."
